services:
  - type: web
    name: ruleta-suerte
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeployTrigger: commit
